### ISSUE TITLE
Question on documentation: testin the pipeline

### ISSUE THREAD

**Issue by telatin** [bhattlab/phanta#1]
Hi and thanks for the tool!

In https://github.com/bhattlab/phanta#test-your-installation you mention

> Edit samp_file.txt by replacing /full/path/to/cloned/repo in the four locations indicated with the full path to your cloned repository.

the file refers to "test_dataset/sample19_R1.fastq.gz" but I dint find those reads in the repository. Can you please suggest where to fetch the test dataset? Thanks a million

**Comment by meenachakra** [comment]
Hi telatin, thank you for your interest in phanta!

Those reads are available in the test dataset that you download using the wget command provided here:

https://github.com/bhattlab/phanta#test-your-installation

Please let us know if you continue to have trouble. Thank you!

**Comment by telatin** [comment]
Silly me! Thanks a million

**Comment by meenachakra** [comment]
Of course! Glad to hear that helped :)
