### ISSUE TITLE
PHANTA fails on single sample because `prep_to_merge_normed.py` expects header

### ISSUE THREAD

**Issue by nickp60** [bhattlab/phanta#12]
Hello! I am trying to run phanta 1.1.0 on a single sample and get an error trying to convert `''` to an int, arising from https://github.com/bhattlab/phanta/blob/0402de670752fcef570a6d19e3c6c86af870d106/pipeline_scripts/prep_to_merge_normed.py#L36.  The issue (I think) is 
https://github.com/bhattlab/phanta/blob/0402de670752fcef570a6d19e3c6c86af870d106/pipeline_scripts/prep_to_merge_normed.py#L9
to get rid of a header row in the total_counts.tsv file.  AFAIK, there is no header in that file, so the first sample in all runs will be excluded by default. 

Am I doing something wrong, or is this a bug?

Thanks!

**Comment by yipinto** [comment]
Thank Nick,
We are testing the single sample now. The final_merged_outputs/total_reads.tsv file does have an header (and we do not experience first sample excluded). will update!

**Comment by nickp60** [comment]
Thanks for looking into it!  I noticed another issue on my system (bc wasn't installed, but the error wasn't raised) that might be to blame as well, will keep you posted.  Apologies in advance if its a red herring!

**Comment by nickp60** [comment]
And yes, missing `bc` was the issue; (this line)[https://github.com/bhattlab/phanta/blob/0402de670752fcef570a6d19e3c6c86af870d106/pipeline_scripts/calc_total_reads.sh#L25] failed but didn't raise an error when piped, which I guess caused the situation with prep_to_merge_normed.py.  User error; my apologies!
