### ISSUE TITLE
Testing installation using demo

### ISSUE THREAD

**Issue by hgingras** [bhattlab/phanta#17]
I have installed the requirements to run the demo files for Phanta analysis.
I run on clusters without conda.

--------------------------------------------

Here is my slurm output:

...
-------- ((modules load and virtualenv prep) all good...) ------- Followed by:
Building DAG of jobs...
MissingRuleException:
No rule to produce / (if you use input functions make sure that they don't raise unexpected exceptions).
sample19	/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/sample19_R1.fastq.gz	/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/sample19_R2.fastq.gz

sample18	/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/sample18_R1.fastq.gz	/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/sample18_R2.fastq.gz

---------------------------------------------
Here is my submission script:

#!/usr/bin/env bash

#SBATCH --account=def-helene
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=0-02:00
#SBATCH --mem=32GB

module load StdEnv/2020 python/3.10 gcc/9.3.0 r/4.2.2 kraken2/2.1.2 bracken/2.6.0

virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
pip install --no-index --upgrade pip
pip install --no-index -r requirements.txt

snakemake -s /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/Snakefile \
 --configfile /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/config_test.yaml \
 --jobs 99 --cores ${SLURM_CPUS_PER_TASK-1} \
/

-------------------------------------------------------
Here is the requirements.txt obtained when installing these wheels in my virtualenv:
pip install --no-index  --upgrade pip
pip install --no-index pandas==2.0.0
pip install --no-index numpy==1.24.2
pip install --no-index snakemake==7.3.8

-------------------------------------------------------
appdirs==1.4.4+computecanada
attrs==23.1.0+computecanada
certifi==2022.12.7+computecanada
charset_normalizer==3.1.0+computecanada
ConfigArgParse==1.5.3+computecanada
connection_pool==0.0.3+computecanada
datrie==0.8.2+computecanada
decorator==5.1.1+computecanada
docutils==0.19+computecanada
dpath==2.0.5+computecanada
fastjsonschema==2.16.3+computecanada
gitdb==4.0.10+computecanada
GitPython==3.1.31+computecanada
idna==3.4+computecanada
Jinja2==3.1.2+computecanada
jsonschema==4.17.3+computecanada
jupyter_core==5.2.0+computecanada
MarkupSafe==2.1.2+computecanada
nbformat==5.7.3+computecanada
numpy==1.24.2+computecanada
pandas==2.0.0+computecanada
plac==1.3.5+computecanada
platformdirs==3.2.0+computecanada
psutil==5.9.4+computecanada
PuLP==2.6.0+computecanada
py==1.11.0+computecanada
pyrsistent==0.19.3+computecanada
python-dateutil==2.8.2+computecanada
pytz==2023.3+computecanada
PyYAML==6.0+computecanada
ratelimiter==1.2.0.post0+computecanada
requests==2.28.2+computecanada
retry==0.9.2+computecanada
six==1.16.0+computecanada
smart_open==6.3.0+computecanada
smmap==5.0.0+computecanada
snakemake==7.3.8+computecanada
stopit==1.1.2+computecanada
tabulate==0.9.0+computecanada
toposort==1.7+computecanada
traitlets==5.9.0+computecanada
tzdata==2023.3+computecanada
urllib3==1.26.15+computecanada
wrapt==1.15.0+computecanada
yte==1.5.1+computecanada

--------------------------------------------

Here is the config_test.yaml with only the lines with changes:

pipeline_directory: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta

sample_file: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/samp_file.txt

outdir: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset

database: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta_dbs/unmasked_db_v1

--------------------------------------------

Did not modified the Snakemake file

--------------------------------------------

I would appreciate if you could tell me what I am doing wrong.

Best regards,

Hélène

**Comment by meenachakra** [comment]
Hi! Thanks for your interest in Phanta! I think you have an extra slash at the end of your snakemake command?

**Comment by hgingras** [comment]
Hi, I have adjusted my command line so there are no confusion, thanks. It is now running for kaken rule for both sample 18 and 19 (here the output example for sample 19):
_____________________________
rule kraken:
[Mon Jun 19 10:07:07 2023]
Finished job 10.
2 of 21 steps (10%) done
Select jobs to execute...
______________________________

Next rule in line is : rule filter_kraken:

This one I have an error about missing output file?

[Mon Jun 19 10:07:07 2023]
rule filter_kraken:
    input: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report
    output: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report.species, /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report.filtered, /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report.filtering_decisions.txt
    jobid: 9
    reason: Missing output files: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report.filtered, /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report.filtering_decisions.txt; Input files updated by another job: /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample18.krak.report
    wildcards: samp=sample18
    resources: tmpdir=/tmp


The thing is that the file sample18.krak.report.filtering_decisions.txt is actually found in this location:

/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/classification/intermediate
sample18.krak.report           
sample18.krak.report.filtered.bracken         
sample19.krak.report           
sample19.krak.report.filtered.bracken
sample18.krak.report.filtered  
sample18.krak.report.filtering_decisions.txt  
sample19.krak.report.filtered  
sample19.krak.report.filtering_decisions.txt

Files in:
/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/classification

sample18.krak.report_bracken_species.filtered  
sample19.krak.report                           
sample19.krak.report.filtered.bracken.scaled
sample18.krak.report  
sample18.krak.report.filtered.bracken.scaled   
sample19.krak.report_bracken_species.filtered  samples_that_failed_bracken.txt

Files in:
/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification

sample18.krak  
sample18.krak.report  
sample19.krak  
sample19.krak.report

Is there something I did wrong in the config_test.yaml? See previous note for the set up. 

Best regards,

Hélène

**Comment by hgingras** [comment]
Also, just so you know, when I run the pipeline with snakemake 7.3.8 as it is recommend in the troubleshooting environment creation section I have this issue:

File "/lustre03/project/6078354/helene/Tickets/0194347/Phanta_ENV_2/lib/python3.10/site-packages/snakemake/rules.py", line 1215, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'

When you look at the phanta_env.yaml it is written  :
- snakemake=7.12.1=hdfd78af_0
- snakemake-minimal=7.12.1=pyhdfd78af_0

Now I am using snakemake 7.20.0 and I do not have this issue.

You may need to update the troubleshooting environment creation section...

Best regards,

Hélène

**Comment by meenachakra** [comment]
Hi! 
-Thank you for the note about the snakemake version, we will update the section.
-I don't think that's an error for the filter_kraken? It's just specifying that's why it will run the job. Is that right? I.e., did you get it to work?

**Comment by hgingras** [comment]
Hi Meenachakra,

This is the error I get in rule filter_kraken::

/lustre03/project/6078354/helene/Tickets/0194347/Phanta_ENV_3/lib/python3.10/site-packages/pandas/core/reshape/merge.py:1204: RuntimeWarning: invalid value encountered in cast
  if not (lk == lk.astype(rk.dtype))[~np.isnan(lk)].all():
/lustre03/project/6078354/helene/Tickets/0194347/Phanta_ENV_3/lib/python3.10/site-packages/pandas/core/reshape/merge.py:1204: RuntimeWarning: invalid value encountered in cast
  if not (lk == lk.astype(rk.dtype))[~np.isnan(lk)].all():
Traceback (most recent call last):
  File "/lustre03/project/6078354/helene/Tickets/0194347/Phanta_ENV_3/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'species_level_taxa'

Thanks for your support,

Hélène

**Comment by hgingras** [comment]
Another question, what is the database required to run the demo? Default database, Prophage masked database or Default database that uses the GTDB taxonomy for bacteria and Archaea?

Thanks,

Hélène

**Comment by meenachakra** [comment]
Hello Hélène,

The default database is required to run the demo. 

What does your kraken output look like - could you paste the first few lines here for each sample? That will help us figure out what's going on. Thank you!

**Comment by meenachakra** [comment]
Thank you for the context and these helpful details! Will think and respond soon.

**Comment by meenachakra** [comment]
Your krak report results look correct. Looks like line 94 in filter_kraken_reports.py (https://github.com/bhattlab/phanta/blob/main/pipeline_scripts/filter_kraken_reports.py) is not working. It's supposed to be creating a new column called species_level_taxa but instead it's somehow maybe trying to access it.

What version of pandas do you have?

**Comment by hgingras** [comment]
Dear Meenachakra, here is what I have installed in Alex environment :

pip install --no-index numpy==1.24.2
pip install --no-index pandas~=1.4.0
pip install snakemake==7.20.0

Here are other modules: 

python/3.10.2 r/4.2.2 kraken2/2.1.2 bracken/2.6.0


And here is the pip list:

appdirs            1.4.4+computecanada
attrs              21.4.0+computecanada
certifi            2022.12.7+computecanada
charset_normalizer 3.1.0+computecanada
colorama           0.4.6
ConfigArgParse     1.5.3+computecanada
connection_pool    0.0.3+computecanada
datrie             0.8.2+computecanada
docutils           0.19+computecanada
dpath              2.0.5+computecanada
fastjsonschema     2.16.3+computecanada
gitdb              4.0.10+computecanada
GitPython          3.1.31+computecanada
humanfriendly      10.0+computecanada
idna               3.4+computecanada
Jinja2             3.1.2+computecanada
jsonschema         4.17.3+computecanada
jupyter_core       5.2.0+computecanada
MarkupSafe         2.1.2+computecanada
more-itertools     8.14.0
nbformat           5.7.3+computecanada
numpy              1.24.2+computecanada
pandas             1.4.1+computecanada
pip                23.1.2
plac               1.3.5+computecanada
platformdirs       3.2.0+computecanada
psutil             5.9.4+computecanada
PuLP               2.6.0+computecanada
Pygments           2.15.1+computecanada
pyrsistent         0.19.3+computecanada
python-dateutil    2.8.2+computecanada
pytz               2023.3+computecanada
PyYAML             6.0+computecanada
requests           2.28.2+computecanada
reretry            0.11.8
setuptools         67.7.2
six                1.16.0+computecanada
smart_open         6.3.0+computecanada
smmap              5.0.0+computecanada
snakeboost         0.3.0
snakemake          7.20.0
stopit             1.1.2+computecanada
tabulate           0.9.0+computecanada
throttler          1.2.2
toposort           1.7+computecanada
traitlets          5.9.0+computecanada
tzdata             2023.3+computecanada
urllib3            1.26.15+computecanada
wheel              0.40.0
wrapt              1.15.0+computecanada
yte                1.5.1+computecanada

**Comment by hgingras** [comment]
I just tried again with :

numpy              1.23.2+computecanada
pandas             1.4.3+computecanada

Full pip list:

appdirs            1.4.4+computecanada
attrs              21.4.0+computecanada
certifi            2022.12.7+computecanada
charset_normalizer 3.1.0+computecanada
colorama           0.4.6
ConfigArgParse     1.5.3+computecanada
connection_pool    0.0.3+computecanada
datrie             0.8.2+computecanada
docutils           0.19+computecanada
dpath              2.0.5+computecanada
fastjsonschema     2.16.3+computecanada
gitdb              4.0.10+computecanada
GitPython          3.1.31+computecanada
humanfriendly      10.0+computecanada
idna               3.4+computecanada
Jinja2             3.1.2+computecanada
jsonschema         4.17.3+computecanada
jupyter_core       5.2.0+computecanada
MarkupSafe         2.1.2+computecanada
more-itertools     8.14.0
nbformat           5.7.3+computecanada
numpy              1.23.2+computecanada
pandas             1.4.3+computecanada
pip                23.1.2
plac               1.3.5+computecanada
platformdirs       3.2.0+computecanada
psutil             5.9.4+computecanada
PuLP               2.6.0+computecanada
Pygments           2.15.1+computecanada
pyrsistent         0.19.3+computecanada
python-dateutil    2.8.2+computecanada
pytz               2023.3+computecanada
PyYAML             6.0+computecanada
requests           2.28.2+computecanada
reretry            0.11.8
setuptools         67.7.2
six                1.16.0+computecanada
smart_open         6.3.0+computecanada
smmap              5.0.0+computecanada
snakeboost         0.3.0
snakemake          7.20.0
stopit             1.1.2+computecanada
tabulate           0.9.0+computecanada
throttler          1.2.2
toposort           1.7+computecanada
traitlets          5.9.0+computecanada
tzdata             2023.3+computecanada
urllib3            1.26.15+computecanada
wheel              0.40.0
wrapt              1.15.0+computecanada
yte                1.5.1+computecanada

We still have KeyError: 'species_level_taxa'

Traceback (most recent call last):
  File "/lustre03/project/6078354/helene/Tickets/0194347/Phanta_ENV_3/lib/python3.10/site-packages/pandas/core/frame.py", line 3799, in _set_item_mgr
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'species_level_taxa'

**Comment by meenachakra** [comment]
Hmm, sorry to hear that! Maybe you can try to run the filter_kraken_reports.py script manually on each report? This is the command to run (from the Snakefile): 

```
python {params.repo_dir}/pipeline_scripts/filter_kraken_reports.py {input.krak_report} {params.db} \
    {params.cov_thresh_bacterial} {params.cov_thresh_viral} {params.minimizer_thresh_bacterial} \
    {params.minimizer_thresh_viral} \
    {params.cov_thresh_arc} {params.cov_thresh_euk} {params.minimizer_thresh_arc} \
    {params.minimizer_thresh_euk}
```

You'll have to replace all the values in brackets - the coverage/minimizer thresholds are the ones specified in your config file.

**Comment by hgingras** [comment]
Hello Meenachakra,

The script:

python /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/pipeline_scripts/filter_kraken_reports.py /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/test_dataset/classification/sample19.krak.report /home/helene/projects/def-helene/helene/Tickets/0194347/phanta_dbs/unmasked_db_v1 0.01 0.1 0 0 0.01 0 0 0

Error message:

Traceback (most recent call last):
  File "/home/helene/projects/def-helene/helene/Tickets/0194347/phanta/pipeline_scripts/filter_kraken_reports.py", line 94, in <module>
    species_kraken['species_level_taxa'] = species_kraken.apply(lambda x: taxid_to_desired_rank(str(x['ncbi_taxonomy']), 'species', child_parent, taxid_rank), axis=1)
  File "/home/helene/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3968, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/helene/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4123, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column species_level_taxa

Thanks for your help,

Hélène

**Comment by meenachakra** [comment]
Interesting!
Could you make a copy of the script and replace `species_kraken['species_level_taxa']` with `test` and then add a line that prints `test`? Seems like the apply function is not working for some reason, not sure why

**Comment by hgingras** [comment]
Hello Meenachakra,

I found something if I use phanta/test_dataset/classification/sample19.krak.report I get the error of DataFrame. When I use phanta/testing/classification/sample19.krak.report from the testing folder, I do not have an error. These two files do not have the same column numbers. Is this info leading to some insight on your side?

From testing/classification/ folder: 8 columns:

0.58  38187   38187   0       0       U       0       unclassified
 99.42  6567731 112023  262847837       52674695        R       1       root
 93.14  6152760 5247    243733167       51177499        R1      131567    cellular organisms
 93.05  6146638 138289  243267882       50791588        D       2           Bacteria
 64.23  4243272 45617   168588127       35106668        D1      1783272       Terrabacteria group
 44.50  2939663 199085  113516718       26961606        P       1239            Firmicutes
 25.51  1685140 2593    59307662        17113555        C       186801            Clostridia
 25.47  1682542 333631  58859090        16872209        O       186802              Clostridiales
 11.77  777759  167129  23625367        6563956 F       541000                Ruminococcaceae
  6.09  402040  152694  10041499        2756044 G       216851                  Faecalibacterium
  2.92  193044  130902  4201973 1278127 S       853                       Faecalibacterium prausnitzii
  0.72  47245   43158   981810  347471  S1      411483                      Faecalibacterium prausnitzii A2-165

From test_dataset/classification folder: 6 columns:

 0.58  38187   38187   U       0       unclassified
 99.42  6567731 112023  R       1       root
 93.14  6152760 5247    R1      131567    cellular organisms
 93.05  6146638 138289  D       2           Bacteria
 64.23  4243272 45617   D1      1783272       Terrabacteria group
 44.50  2939663 199085  P       1239            Firmicutes
 25.51  1685140 2593    C       186801            Clostridia
 25.47  1682542 333631  O       186802              Clostridiales
 11.77  777759  167129  F       541000                Ruminococcaceae
  6.09  402040  152694  G       216851                  Faecalibacterium
  2.92  193044  130902  S       853                       Faecalibacterium prausnitzii
  0.72  47245   43158   S1      411483                      Faecalibacterium prausnitzii A2-165

Best regards,

Helene

**Comment by hgingras** [comment]
I have been trying to download other databases but not able to. Anything wrong with the severs? I was using the database suggested in the Quick start section. http://ab_phanta.os.scg.stanford.edu/Phanta_DBs/database_V1.tar.gz

We have 6 columns here.
First few lines in this file phanta_dbs/unmasked_db_v1/inspect.out

  0.00  0       0       U       0       unclassified
100.00  5657704547      83283590        R       1       root
 90.98  5147592210      2795098 R1      131567    cellular organisms
 69.58  3936411473      63905134        D       2           Bacteria
 44.92  2541363642      13519023        D1      1783272       Terrabacteria group
 38.85  2198170416      72921856        P       1239            Firmicutes
 26.88  1520611030      2145516 C       186801            Clostridia
 26.59  1504398150      86242030        O       186802              Clostridiales
  6.71  379420572       17289207        F       541000                Ruminococcaceae
  1.51  85357482        0       F1      541002                  environmental samples
  1.51  85357482        24512736        S       541003                    uncultured Ruminococcaceae bacterium

I guess it has to do with the database... the script may not be universal?

**Comment by meenachakra** [comment]
Oh, that's very informative that the columns are different! Didn't notice that in the first glance. That indicates that your kraken isn't reporting unique minimizer data which is required for the filtering step (please see our paper).

Could you try running just kraken in your environment?

This is the command to run (from the Snakefile)

```
kraken2 --db {params.db} --threads {threads} --output {output.krak} \
--report {output.krak_report} --report-minimizer-data {params.paired_string} \
{params.gzipped_string} {input.reads} --confidence {params.confidence_threshold}
```
You need to replace everything in brackets.

- params.db is the path to your database
- threads is the max number of threads you have available to run the command
- output.krak is your desired name of the .krak file that will be produced
- output.krak.report is your desired name of the .krak.report file that will be produced
- params.paired_string is '--paired' if you have paired end reads, otherwise nothing
- params.gzipped_string is '--gzip-compressed' or nothing
- input.reads is the two names of the paired end read files (Forward and reverse), separated by a space [unless your reads are not paired end]
- confidence threshold is the confidence threshold you specified in the config

**Comment by meenachakra** [comment]
And - thank you for letting us know about the servers! Indeed, some of the servers at our university are currently down till Monday for maintenance - we should indicate that on the README! Thanks!

**Comment by hgingras** [comment]
Dear Meenachakra:

Run this:

kraken2 --db /home/helene/projects/def-helene/helene/Tickets/0194347/phanta_dbs/unmasked_db_v1 --threads 1 --output output.krak --report report.output.krak --report-minimizer-data --paired --gzip-compressed /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/sample18_R1.fastq.gz /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/sample18_R2.fastq.gz --confidence 0.1

Got this message:
Unknown option: report-minimizer-data
Loading database information...classify: Error reading in hash table

Run again (without --report-minimizer-data):
kraken2 --db /home/helene/projects/def-helene/helene/Tickets/0194347/phanta_dbs/unmasked_db_v1 --threads 1 --output output.krak --report report.output.krak --paired --gzip-compressed /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/sample18_R1.fastq.gz /home/helene/projects/def-helene/helene/Tickets/0194347/phanta/testing/sample18_R2.fastq.gz --confidence 0.1

Got this message:
Loading database information...classify: Error reading in hash table

**Comment by meenachakra** [comment]
Thanks! The error reading in hash table is because you don't have enough available memory.

You need at least 32GB memory available to run the command (which you must have available on your system, since you ran kraken before successfully with the Snakefile).  

For the unknown option: that's strange!

It's a relatively new feature in Kraken2... but 2.1.2 is indeed the version we used.

Could you try to not load Kraken2 in your environment and just load bracken (and use v2.7 rather than 2.6.0 for that)? As far as I recall, installing Bracken installs Kraken2 by default.

**Comment by hgingras** [comment]
Dear Meenachakra, 

I ran again with bracken v.2.7 and it worked perfectly. 

Thanks again for all your help.

Hélène

**Comment by meenachakra** [comment]
Perfect!! That's great to hear. Good luck running Phanta on your samples.
