### ISSUE TITLE
Other link for DB?

### ISSUE THREAD

**Issue by Sanrrone** [bhattlab/phanta#20]
Dears,
This is software is exactly what I am looking for but, is there other link to download the DBs? service is still unavailable besides the maintenance.

thanks in advance!
Sandro

**Comment by meenachakra** [comment]
Thanks Sandro!
We contacted our server admins and they are looking into it. If they can't resolve it within a few days, then we can look into other services. Hopefully, it will be solved soon!

**Comment by yipinto** [comment]
I was fixed now. Please try again and contact us if you are still facing problems with downloading the db.
Sorry for the inconvenience.
