### ISSUE TITLE
Family level is missing for some viruses

### ISSUE THREAD

**Issue by Sanrrone** [bhattlab/phanta#22]
Hi!,
I am testing some of my samples and I noticed in some cases the taxonomy is incomplete, family level is missing in the tax definition. for example:
```
no rank_root|superkingdom_Viruses|clade_Duplodnaviria|kingdom_Heunggongvirae|phylum_Uroviricota|class_Caudoviricetes|order_Caudovirales|genus_mgv_g_4000038|species_OTU-75737	no rank_1|superkingdom_10239|clade_2731341|kingdom_2731360|phylum_2731618|class_2731619|order_28883|genus_4000038|species_4045745	0	7.03870548962311e-05
```
is there a parameter to fill it? just to complete the taxonomy like `family_unknown`

thanks in advance!

**Comment by yipinto** [comment]
Hi!
Unfortunately, there is no argument to fill the unknown taxonomy. We will consider to add that in the next version of Phanta.



On Jul 10, 2023 05:03, Sandro Valenzuela ***@***.***> wrote:

Hi!,
I am testing some of my samples and I noticed in some cases the taxonomy is incomplete, family level is missing in the tax definition. for example:

no rank_root|superkingdom_Viruses|clade_Duplodnaviria|kingdom_Heunggongvirae|phylum_Uroviricota|class_Caudoviricetes|order_Caudovirales|genus_mgv_g_4000038|species_OTU-75737   no rank_1|superkingdom_10239|clade_2731341|kingdom_2731360|phylum_2731618|class_2731619|order_28883|genus_4000038|species_4045745       0       7.03870548962311e-05


is there a parameter to fill it? just to complete the taxonomy like family_unknown

thanks in advance!

**Comment by meenachakra** [comment]
That's a great idea, thank you! As Yishay said we will consider to add this in the next version of Phanta.
