### ISSUE TITLE
How to run it using SLURM

### ISSUE THREAD

**Issue by Sanrrone** [bhattlab/phanta#23]
Dears,
I am trying to run multiple samples but I cannot find the correct documentation about run the jobs using slurm. I noticed that using the pipeline following the documentation led to serialize the samples instead of run multiple instances. Is it possible to submit slurm jobs for each instance? how could I configure the files to make it?.

thanks in advance!.

**Comment by meenachakra** [comment]
Hi Sandro,

Thanks for the question! We have been using slurm to run Phanta for multiple samples and they run in parallel. Do you have multiple samples listed in your sample file?

**Comment by Sanrrone** [comment]
yes, but I am not sure how to configure it to make it work with slurm. could you share the config file?

**Comment by yipinto** [comment]
Phanta's config will be the same. 
You can get the slurm snakemake [profile ](https://github.com/Snakemake-Profiles/) (also see in Phanta's manual) or follow the suggestions [here](https://snakemake.readthedocs.io/en/stable/executing/cluster.html).
Let us know if that helps

**Comment by yipinto** [comment]
@Sanrrone, I'm closing this issue.
You may open it to share how you solve it or if you have any further questions!
