### ISSUE TITLE
Filter out host/contaminant genome?

### ISSUE THREAD

**Issue by mhmism** [bhattlab/phanta#27]
Thank you for this amazing tool!

Should we filter out the host (human) genome before executing the pipeline e.g. using kneadData or fastp? the same also applies to the PhiX genomes?

Thank you in advance!

**Comment by yipinto** [comment]
Hi,
Thanks!
Yes I believe that filtering host contamination before executing Phanta is a good practice, although Phanta database contains the human genome, and the human reads will most probably be filtered down the road anyway.
We do recommend additional pre-processing steps like trimming end, removing low quality and duplicated reads as well.

**Comment by mhmism** [comment]
Thanks!
