### ISSUE TITLE
Environment file

### ISSUE THREAD

**Issue by telatin** [bhattlab/phanta#28]
Hi, I tried to create the environment using the environment file but got some issues:

1) When conda is configured for strict channel priority, it fails. 

2) When removing the strict channel priority setting, I get an error related to openssl. I guess the version that was installed at the time of the generation of the YAML file is no longer available

```text
 - package cryptography-37.0.1-py310h9ce1e76_0 requires openssl <1.1.2a, but none of the providers can be installed
```

3) When tweaking the file to install cryptography 38.0, the pipeline fails. Checking the logs is because a script uses `bc` which is not installed with the conda environment (and may not be available on the system). The missing `bc` didn't cause an error, but rather and empty value in the file which led to a failure downstream (prep_to_merge_normed.py).

I made a PR to address these issues if needed

**Comment by yipinto** [comment]
Thank you! We will review the PR and merge.

**Comment by meenachakra** [comment]
Thanks, done!

**Comment by meenachakra** [comment]
Thanks, done!
