### ISSUE TITLE
The library fna file

### ISSUE THREAD

**Issue by alienzj** [bhattlab/phanta#31]
Hi, may I know can you provilde the library file that used to construct kraken2 database?
I didn't found it after downloaded the database and uncompressed it.

**Comment by yipinto** [comment]
Hi,
The fasta files for the library are not provided as part of the database as they are not needed for running Phanta.
We do plan to upload them and make them available sometime soon for users that wish to build a custom DB.
In the meanwhile, you can either download the sequences from MGV and HumGut or alternatively email @meenachakra (see https://www.bhattlab.com/people) and she can help you with that.

**Comment by alienzj** [comment]
Hi,
thanks for your quick reply.

The reason why the fasta file is needed is that I want to continue to study the strain transmission based on the results of phanta profiling. Many downstream analyzes in this area need to call snp based on the genome database, which is to maintain the consistency of the method and database.

**Comment by yipinto** [comment]
hi @alienzj,
You can find the fna files here:
wget http://ab_phanta.os.scg.stanford.edu/Phanta_DBs/database_V1.library.tar.gz
Notice that Phanta information is limited to the species level. 
Good luck!

**Comment by alienzj** [comment]
Hi @yipinto 
Thank you and your team so much!
