### ISSUE TITLE
Question about the database species

### ISSUE THREAD

**Issue by Iris7788** [bhattlab/phanta#33]
hi, 

I have downloaded the unmasked_db_v1. I would like to know the viral species covered in the database. I noticed that the file “seqid2taxid.map” in the database folder can map genome names to taxa IDs. However, I found that the taxa IDs corresponding to genomes from MGV cannot retrieve the corresponding lineage information on the NCBI website.
is there a solution to get it?

**Comment by meenachakra** [comment]
Hi, you can get the lineage information from the names/nodes file in the taxonomy subfolder. These files are in the standard format for names/nodes files for Kraken2 databases - e.g., see this link - https://github.com/DerrickWood/kraken2/issues/436. Please see the methods section of our paper for how taxonomic assignments were made for each viral genome. Hope this helps!

**Comment by Iris7788** [comment]
你的邮件我已经收到啦，我会尽快查收哒~

**Comment by Iris7788** [comment]
Thank you for your kind reply. I also want to know if phanta will provide host, and lifestyle information for predicted phage.

**Comment by meenachakra** [comment]
Hi, of course. Yes the host and lifestyle information is contained within the DB as species_name_to_vir_score.txt and host_prediction_to_genus.tsv.
