### ISSUE TITLE
Question about human-infecting viruses

### ISSUE THREAD

**Issue by camilagazolla** [bhattlab/phanta#37]
Thank you very much for phanta development.

I notice that in the phanta manuscript you also analysed human-infecting viruses.

Do you know what would be a good way to split phanta output for i) human-infecting viruses and ii) phages?

Thank you!

**Comment by yipinto** [comment]
Human infecting viruses are usually in different lineages than bacteriophages, so you can try use that information.
Another alternative is to downloads the taxonomy ID of human infecting viruses and intersect it with Phanta results.
