### ISSUE TITLE
[ICTV taxonomy] New taxonomy on the database

### ISSUE THREAD

**Issue by rdenise** [bhattlab/phanta#38]
Upon executing Phanta, I observed that the taxonomy names displayed are consistent with the older nomenclature, such as Podoviridae, Myoviridae, and Siphoviridae. Is it feasible to request an update to the database that aligns with the revised ICTV taxonomy, a practice similarly implemented in IMG/VR and RefSeq?

**Comment by meenachakra** [comment]
Hello, thank you for bringing this to our attention! We have recently created a few new databases (see https://github.com/bhattlab/phanta/blob/main/databases.md), including those that include the expanded viral genome catalog UHGV (https://github.com/snayfach/UHGV). In the UHGV-based databases, the viral genomes have ICTV taxonomy specified up to the order level.
