### ISSUE TITLE
DB cannot be loaded

### ISSUE THREAD

**Issue by StfnRomano** [bhattlab/phanta#6]
Hi,

thank you for this very useful tool.
I have been using it for a few weeks now and it works very well.
I have a dataset for which it doesn't seem to run properly though, and I did not manage to figure out why.

Basically the workflow starts but then it seems to not be able to load the DB:
```
Loading database information... done.
0 sequences (0.00 Mbp) processed in 0.001s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)
Waiting at most 250 seconds for missing files.

MissingOutputException in line 77 of /software/envs/phanta/Snakefile:
Job Missing files after 250 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/scratch/phanta/classification/D_clean_conc_SE.krak completed successfully, but some output files are missing. 125

```

I am  not sure why this is the case, and I double checked all the paths and all is where is supposed to be. 
Do you guys have any tips on how to go around this?

Thank you
Stefano

**Comment by meenachakra** [comment]
Hi Stefano,

Thank you for the question, glad the tool is working well for you! Just to ask the first question that comes to mind, how many reads are in the sample you are trying to classify?

**Comment by StfnRomano** [comment]
Hi,

thank you so much for the message and sorry for the late reply. Indeed there were issues with my input files. Two names were merged and one file was huge and another empty. I fixed this and now all worked well.

Thank you!
I will close this
Stefano
