### ISSUE TITLE
Unique Permutation Warning Requires Manual Input

### ISSUE THREAD

**Issue by vzg100** [bhattlab/phanta#8]
When running the steps for the calculating the cross domain correlation I sometimes see this error: `Warning: the following OTUs have only one unique permutation and it is recommended to remove them from this analysis:` requires a manual Y/N input. 

However when running these scripts on a SLURM job, manual input isn't always possible. Is there a flag or method to bypass with a flag that automatically accepts or removes the OTU from the analysis?

**Comment by meenachakra** [comment]
Great question, thank you for the question! Tagging @yipinto for help with this issue.

**Comment by yipinto** [comment]
Hi @vzg100,
Can you please paste the commands you used? and also number taxon in your table. It will help me to better understand why it happens.
Thanks!
